# This is a basic workflow to help you get started with Actions
name: Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v1.1
        with:
          architecture: 'x64'
          variant: 'CS'
          version: '8.0'
          # NOTE: try to cache /usr/share/racket-8.0.0.12/
          packages: 'semilit', 'nanopass', 'riposte'
      - name: Build
        run: |
          make build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: master
          cname: racket.tw
